version: "3.7"
services:
  app:
    build:
      context: ./containers/app/
      args:
        GIT_URL: "https://github.com/isucon/isucon7-qualify.git"
    tty: true
    ports:
      - "5000"
    environment:
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
      ISUBATA_DB_HOST: db
    depends_on:
      - db
    networks:
      - backend
  db:
    build:
      context: ./containers/db
      args:
        GIT_URL: "https://github.com/isucon/isucon7-qualify.git"
    tty: true
    ports:
      - "3306"
    networks:
      - backend
  web:
    build:
      context: ./containers/nginx
    tty: true
    depends_on:
      - app
    ports:
      - "3000:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
